apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-db-pvc
spec:
  storageClassName: "local-storage"
  volumeName: example-db-pv
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi